version: "3.1"
services:
  _mqtt-gpio-switcher_build:
    image: mqtt-gpio-switcher
    command: ['echo', 'build completed']
    build: mqtt-gpio-switcher

  lights-driver:
    image: mqtt-gpio-switcher
    depends_on:
        - _mqtt-gpio-switcher_build
    network_mode: "host"
    privileged: true
    command: lamp 1 17

  fan-driver-1:
    image: mqtt-gpio-switcher
    depends_on:
        - _mqtt-gpio-switcher_build
    network_mode: "host"
    privileged: true
    command: fan 1 13

  fan-driver-2:
    image: mqtt-gpio-switcher
    depends_on:
        - _mqtt-gpio-switcher_build
    network_mode: "host"
    privileged: true
    command: fan 2 19

  fan-driver-3:
    image: mqtt-gpio-switcher
    depends_on:
        - _mqtt-gpio-switcher_build
    network_mode: "host"
    privileged: true
    command: fan 3 26
