version: "3.1"
services:
  lights-driver:
    build: mqtt-gpio-switcher
    network_mode: "host"
    privileged: true
    command: lamp 1 22
  fan-driver-1:
    build: mqtt-gpio-switcher
    network_mode: "host"
    privileged: true
    command: fan 1 13
  fan-driver-2:
    build: mqtt-gpio-switcher
    network_mode: "host"
    privileged: true
    command: fan 2 19
  fan-driver-3:
    build: mqtt-gpio-switcher
    network_mode: "host"
    privileged: true
    command: fan 3 26
